"""添加file_name字段

Revision ID: dd5dddd60425
Revises: 1404f74ac8a3
Create Date: 2021-06-11 00:37:04.857446

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'dd5dddd60425'
down_revision = '1404f74ac8a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('file_name', sa.String(100), nullable = False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'file_name')
    # ### end Alembic commands ###
